{% set version = "1.4.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gh
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gh_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gh/gh_{{ version }}.tar.gz
  sha256: 76bd3f2a31eeaf76a633362899a20b0f7e8fb6159d4777baf3da2a47854292af

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli >=3.0.1
    - r-gitcreds
    - r-httr2
    - r-ini
    - r-jsonlite
    - r-rlang >=1.0.0
  run:
    - r-base
    - r-cli >=3.0.1
    - r-gitcreds
    - r-httr2
    - r-ini
    - r-jsonlite
    - r-rlang >=1.0.0

test:
  commands:
    - $R -e "library('gh')"           # [not win]
    - "\"%R%\" -e \"library('gh')\""  # [win]

about:
  home: https://gh.r-lib.org/, https://github.com/r-lib/gh#readme
  license: MIT
  summary: Minimal client to access the 'GitHub' 'API'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
